### ISSUE TITLE
Дальняя атака для enemy

### ISSUE THREAD

**Issue by Keallar** [Keallar/Ragnarok#28]

**Comment by SleepingException** [comment]
ABUBU

**Comment by Legida** [comment]
первый прототип атаки сделал, стреляет в направлении, куда мышкой нажал. Есть класс пули (bullet) и класс, который создает эти пули (bulletFactory). Удаление и апдейт пули происходит в сцене (пока что). Пули проходят через игрока (пока что все, потом только пули игрока). Пули имеют время жизни, игрок имеет время перезарядки между выстрелами.
