### ISSUE TITLE
Экран "Game Over"

### ISSUE THREAD

**Issue by Keallar** [Keallar/Ragnarok#29]

**Comment by SleepingException** [comment]
Это член дружбы добавь его..„--~*'¯…….'\
Своим лучшим друзьям на („-~~--„¸_….,/ì'Ì
Стенку.Чем больше хуев„-^"¯ : : : : :¸-¯"¯/'
Тем ты пизже друг¸„„-^"¯ : : : : : : : '\¸„„,-"
**¯¯¯'^^~-„„„----~^*'"¯ : : : : : : : : : :¸-"
.:.:.:.:.„-^" : : : : : : : : : : : : : : : : :„-"
:.:.:.:.:.:.:.:.:.:.: : : : : : : : : : ¸„-^¯
.::.:.:.:.:.:.:.:. : : : : : : : ¸„„-^¯
:.' : : '\ : : : : : : : ;¸„„-~"¯
:.:.:: :"-„""***/*'ì¸'¯
:.': : : : :"-„ : : :"\
.:.:.: : : : :" : : : : \,
:.: : : : : : : : : : : : 'Ì
: : : : : : :, : : : : : :/
"-„_::::_„-*__„„~"
