### ISSUE TITLE
Смерть player

### ISSUE THREAD

**Issue by Keallar** [Keallar/Ragnarok#30]

**Comment by AlexOsi02** [comment]
Рецепт утки по-пекински:
Разморозить утку, выложив за 2 дня до приготовления из морозилки в холодильник, затем еще 10ч выдержать ее при комнатной температуре.
Промыть утку проточной холодной водой, удалить волоски, если есть.
С помощью острого ножа срезать верхние фаланги крыльев утки, срезать лишний жир в области шеи и гузки.
Подвесить утку на вилку, пролить кипятком со всех сторон, обсушить, затем натереть со всех сторон хересом изнутри и снаружи, оставить на 10мин при комнатной температуре.
Натереть утку солью, затем вставить в нее стакан и поставить утку на блюдо, убрать на 12ч в холодильник, за это время собирающуюся на блюде под уткой жидкость несколько раз слить.
Обмазать выдержанную утку медом равномерным тонким слоем, убрать в холодильник еще на 12ч.
Налить воду в противень, над которым будет запекаться утка, разогреть духовку до 190 градусов, грудкой вверх уложить утку на решетку над противнем, всю конструкцию (противень, решетку и утку на ней) закрыть фольгой так, чтобы не было отверстий, поставить в духовку и запекать 60-70мин.
Соединить имбирь с кунжутным маслом, соевым соусом и перцем, перемешать.
Достать утку из духовки, убрать противень и фольгу, смазать с помощью кулинарной кисточки утку приготовленной имбирной смесью, выложить обратно на решетку, поставить в духовку, повысить температуру до 260 градусов и запекать еще 25мин, следя, чтобы она не подгорала – если начинает подгорать, то убавить температуру или сократить время.
Соединить дополнительно соевый соус и мед, хорошо взбить, открыть духовку и обмазать утку, затем включить режим гриль и запекать еще 10мин до хрустящей золотистой корочки.
Вытащить готовую утку, остудить, нарезать порционными кусочками и подать к столу.
Приятного аппетита!

**Comment by SleepingException** [comment]
Быстрый плов из свинины 4 порции 1 час
Этот рецепт, так сказать, по мотивам настоящего узбекского плова. Для тех, кто не ест свинину, я рекомендую сделать рецепт с курицей. Быстро и вкусно.
Продукты (на 4 порции)Свинина (или курица) - 600 гРис - 1,5 стаканаМорковь - 1 шт.Лук репчатый - 2 шт.Масло растительное - 30 гСоль - по вкусуПерец - по вкусуСахар - 0,5 ч. ложкиПриправа для плова - 0,5 ч. ложкиПошаговый фото рецептБыстрый плов из свининыКак приготовить плов из свинины:Свинину вымыть, обсушить.Мясо разрезать на порционные кусочки, размером около 2х2 см.Разогреть сковороду, налить растительное масло. Выложить мясо. Жарить на среднем огне до золотистой корочки, переворачивая кусочки (минут 10-15).Очистить и помыть морковь. Морковь натереть на крупной терке или нарезать тонкой соломкой.Очистить, помыть лук, нарезать мелко кубиками или тонкими полукольцами.Подготовленное мясо выложить в казанок. В сковороду в горячее масло выложить морковь и лук. Тушить, помешивая, на среднем огне 2-3 минуты. К мясу в казанок выложить зажарку.Вскипятить чайник. Мясо с овощами в казанке перемешать. Посолить, поперчить, добавить любимые специи, сахар. Перемешать. Залить кипятком. Довести до кипения.Рис, желательно длиннозерный, хорошо промыть. Выложить на мясо. Если есть необходимость, добавить кипятка. Рис должен покрываться водой на 2 пальца. Накрыть крышкой, убавить огонь до минимального. Варить плов из свинины до готовности риса, около 40-45 минут.Быстрый плов из свинины готов.Приятного аппетита! | Продукты (на 4 порции)Свинина (или курица) - 600 гРис - 1,5 стаканаМорковь - 1 шт.Лук репчатый - 2 шт.Масло растительное - 30 гСоль - по вкусуПерец - по вкусуСахар - 0,5 ч. ложкиПриправа для плова - 0,5 ч. ложки | Продукты (на 4 порции) | Свинина (или курица) - 600 г | Рис - 1,5 стакана | Морковь - 1 шт. | Лук репчатый - 2 шт. | Масло растительное - 30 г | Соль - по вкусу | Перец - по вкусу | Сахар - 0,5 ч. ложки | Приправа для плова - 0,5 ч. ложки |  
Продукты (на 4 порции)Свинина (или курица) - 600 гРис - 1,5 стаканаМорковь - 1 шт.Лук репчатый - 2 шт.Масло растительное - 30 гСоль - по вкусуПерец - по вкусуСахар - 0,5 ч. ложкиПриправа для плова - 0,5 ч. ложки | Продукты (на 4 порции) | Свинина (или курица) - 600 г | Рис - 1,5 стакана | Морковь - 1 шт. | Лук репчатый - 2 шт. | Масло растительное - 30 г | Соль - по вкусу | Перец - по вкусу | Сахар - 0,5 ч. ложки | Приправа для плова - 0,5 ч. ложки |  
Продукты (на 4 порции)
Свинина (или курица) - 600 г
Рис - 1,5 стакана
Морковь - 1 шт.
Лук репчатый - 2 шт.
Масло растительное - 30 г
Соль - по вкусу
Перец - по вкусу
Сахар - 0,5 ч. ложки
Приправа для плова - 0,5 ч. ложки
